import { writeFile } from 'node:fs/promises';
import type { PromptResponse } from '../types.ts';

const DEFAULT_BASE_URL = 'https://api.promptlycms.com';

export const extractTemplateVariables = (text: string): string[] => {
  const matches = text.matchAll(/\$\{(\w+)\}/g);
  const vars = new Set<string>();
  for (const match of matches) {
    const captured = match[1];
    if (captured) {
      vars.add(captured);
    }
  }
  return [...vars];
};

export const fetchAllPrompts = async (
  apiKey: string,
  baseUrl?: string,
): Promise<PromptResponse[]> => {
  const url = new URL('/prompts', baseUrl ?? DEFAULT_BASE_URL);

  const response = await fetch(url.toString(), {
    headers: {
      Authorization: `Bearer ${apiKey}`,
    },
  });

  if (!response.ok) {
    throw new Error(
      `Failed to fetch prompts: ${response.status} ${response.statusText}`,
    );
  }

  return response.json() as Promise<PromptResponse[]>;
};

export const generateTypeDeclaration = (prompts: PromptResponse[]): string => {
  const lines: string[] = [
    '// Auto-generated by @promptlycms/prompts — do not edit',
    "import '@promptlycms/prompts';",
    '',
    "declare module '@promptlycms/prompts' {",
    '  interface PromptVariableMap {',
  ];

  for (const prompt of prompts) {
    const variables = extractTemplateVariables(prompt.userMessage);
    if (variables.length === 0) {
      lines.push(`    '${prompt.promptId}': Record<string, never>;`);
    } else {
      lines.push(`    '${prompt.promptId}': {`);
      for (const v of variables) {
        lines.push(`      ${v}: string;`);
      }
      lines.push('    };');
    }
  }

  lines.push('  }');
  lines.push('}');
  lines.push('');

  return lines.join('\n');
};

export const generate = async (
  apiKey: string,
  outputPath: string,
  baseUrl?: string,
): Promise<void> => {
  const prompts = await fetchAllPrompts(apiKey, baseUrl);

  if (prompts.length === 0) {
    console.log('  No prompts found for this API key.');
    return;
  }

  console.log(`  Found ${prompts.length} prompt(s)`);

  const content = generateTypeDeclaration(prompts);
  await writeFile(outputPath, content, 'utf-8');
  console.log(`  Generated ${outputPath}`);
};
