import { expect, test } from 'bun:test';
import {
  extractTemplateVariables,
  generateTypeDeclaration,
} from '../cli/generate.ts';
import type { PromptResponse } from '../types.ts';

const makePrompt = (
  overrides: Partial<PromptResponse> = {},
): PromptResponse => ({
  promptId: 'test-id-123',
  promptName: 'Test Prompt',
  version: '1.0.0',
  systemMessage: 'You are a helpful assistant.',
  // biome-ignore lint/suspicious/noTemplateCurlyInString: CMS template variable syntax
  userMessage: 'Hello ${name}, help with ${task}.',
  config: {
    model: 'claude-haiku-4.5',
    temperature: 0.7,
    schema: [],
    inputData: null,
    inputDataRootName: null,
  },
  ...overrides,
});

// --- extractTemplateVariables ---

test('extractTemplateVariables: extracts variables from template string', () => {
  // biome-ignore lint/suspicious/noTemplateCurlyInString: CMS template variable syntax
  const result = extractTemplateVariables('Hello ${name}, help with ${task}.');
  expect(result).toEqual(['name', 'task']);
});

test('extractTemplateVariables: returns empty array for no variables', () => {
  const result = extractTemplateVariables('Hello world.');
  expect(result).toEqual([]);
});

test('extractTemplateVariables: deduplicates repeated variables', () => {
  // biome-ignore lint/suspicious/noTemplateCurlyInString: CMS template variable syntax
  const result = extractTemplateVariables('${name} and ${name} and ${other}');
  expect(result).toEqual(['name', 'other']);
});

// --- generateTypeDeclaration ---

test('generateTypeDeclaration: generates correct declare module block', () => {
  const prompts = [makePrompt()];
  const result = generateTypeDeclaration(prompts);

  expect(result).toContain(
    '// Auto-generated by @promptlycms/prompts — do not edit',
  );
  expect(result).toContain("import '@promptlycms/prompts';");
  expect(result).toContain("declare module '@promptlycms/prompts' {");
  expect(result).toContain('interface PromptVariableMap {');
  expect(result).toContain("'test-id-123': {");
  expect(result).toContain('name: string;');
  expect(result).toContain('task: string;');
});

test('generateTypeDeclaration: handles prompts with no template variables', () => {
  const prompts = [
    makePrompt({
      promptId: 'no-vars',
      userMessage: 'Hello world, no variables here.',
    }),
  ];
  const result = generateTypeDeclaration(prompts);

  expect(result).toContain("'no-vars': Record<string, never>;");
});

test('generateTypeDeclaration: handles multiple prompts', () => {
  const prompts = [
    makePrompt({
      promptId: 'prompt-a',
      // biome-ignore lint/suspicious/noTemplateCurlyInString: CMS template variable syntax
      userMessage: 'Hello ${name}.',
    }),
    makePrompt({
      promptId: 'prompt-b',
      // biome-ignore lint/suspicious/noTemplateCurlyInString: CMS template variable syntax
      userMessage: 'Email ${email} about ${subject}.',
    }),
  ];
  const result = generateTypeDeclaration(prompts);

  expect(result).toContain("'prompt-a': {");
  expect(result).toContain('name: string;');
  expect(result).toContain("'prompt-b': {");
  expect(result).toContain('email: string;');
  expect(result).toContain('subject: string;');
});

test('generateTypeDeclaration: generates valid TypeScript syntax', () => {
  const prompts = [
    makePrompt({
      promptId: 'JPxlUpstuhXB5OwOtKPpj',
      userMessage:
        // biome-ignore lint/suspicious/noTemplateCurlyInString: CMS template variable syntax
        '${pickupLocation} with ${items} and ${movesCount} in ${movesTimePeriod}',
    }),
  ];
  const result = generateTypeDeclaration(prompts);

  const expected = `// Auto-generated by @promptlycms/prompts — do not edit
import '@promptlycms/prompts';

declare module '@promptlycms/prompts' {
  interface PromptVariableMap {
    // v1.0.0
    'JPxlUpstuhXB5OwOtKPpj': {
      pickupLocation: string;
      items: string;
      movesCount: string;
      movesTimePeriod: string;
    };
  }
}
`;

  expect(result).toBe(expected);
});
